### PR TITLE
Heroku button

### PR DESCRIPTION
**Pull request by matiassingers**
One-click setup on Heroku!

### CODE REVIEW

**Comment by marcelkalveram** [comment]
That's a great idea. I've also fixed the failing Travis build, it was lacking some env variables.

**Comment by matiassingers** [comment]
Awesome @marcelkalveram! :+1:

**Comment by jonlay** [comment]
:wave: hello @matiassingers

**Comment by matiassingers** [comment]
yo @jonlay! let me know next time you are in Singapore, grab a :beer:

**Pull request merged**
