### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by everett-wetchler**

### CODE REVIEW

**Comment by everett-wetchler** [comment]
Sorry, meant to push to my fork

**Comment by jonlay** [comment]
@everett-wetchler heh, no trouble!

Looks like a bunch of your stuff is customisations for yourself, which makes total sense, but if you think you've managed to fix some crashes that'll affect others, we'd love a pull request so we can include them. 

Or if you can't unpick the changes, then even a summary of what you were working to fix might, as it'll help give us some context if someone else hits the same frustrations.

p.s. Looks like you guys are doing some awesome socially positive stuff over there at Bayes!

**Comment by everett-wetchler** [comment]
Thanks -- yeah I'm having a few different issues, which I'll sit down to investigate soon. When I have them well defined and replicable, I'll create issues to track, and hopefully send PRs to fix them.

Best, Everett

**Comment by jonlay** [comment]
Beautiful--massively appreciated!

**Pull request closed without merging**
